### PR TITLE
TcpListener::incoming should be by reference

### PR DESCRIPTION
**Pull request by withoutboats**

### CODE REVIEW

**Comment by Diggsey** [comment]
What will the behaviour be if you call `.incoming()` twice, and then have two threads iterate over it in parallel? Won't it only ever wake up whichever thread polled second, and then the first thread will hang forever?

**Comment by withoutboats** [comment]
That's accurate! In contrast, the behavior of std's TcpListener would be to balance incoming requests across both iterators. Not ideal, certainly.

**Comment by Diggsey** [comment]
Yeah, it makes me think that taking ownership, or at least a mutable reference might be preferable, at least until that issue is addressed...

**Comment by withoutboats** [comment]
Consulted with @alexcrichton and agreed that this should be `&mut` to avoid the Sync misuse.

**Comment by yazaddaruvala** [comment]
@withoutboats at that point, I'm back to my original question. Is there really value to the struct `Incoming`? In both cases below, the ergonomics now seem the same.

If `impl Stream for TcpListener`:
```rust
let mut listener: TcpListener = ...;
for await _ in &mut listener {
    // listener.local_addr(); // Will not compile
}
listener.local_addr();
```

If `impl Stream for Incomming`:
```rust
let mut listener: TcpListener = ...;
for await _ in listener.incomming() {
    // listener.local_addr(); // Will not compile
}
listener.local_addr();
```

Meanwhile, as someone less experienced, not only does removing `Incoming` reduce API surface which is nice for learning, but also when not using `for` loops, the ergonomics of `impl Stream for TcpListener` feel better for me (showcased in the changed examples [here](https://github.com/withoutboats/romio/pull/47)).

**Comment by withoutboats** [comment]
@yazaddaruvala It would have to be an `impl Stream for &'a mut TcpListener` which would be a very odd impl. I think using an adapter for stream impls is a better approach. Also, I think there's a lot to be said for keeping the API as close to std as possible.

**Comment by yazaddaruvala** [comment]
My bad, I forgot to mention that std would need to `impl <S: Stream> Stream for &mut S` like it does for `Iterator`.

**Pull request merged**
