### PR TITLE
Add tokio as an alternative to romio

### PR DESCRIPTION
**Pull request by kpp**
async-std was listed as an alternative in https://github.com/withoutboats/romio/pull/105 although Tokio has gained async/await support some time ago and is used extensively in production

### CODE REVIEW

**Comment by spacejam** [comment]
очевидный троллинг...

**Comment by kpp** [comment]
Maybe these thumbs up tell you that this PR is what the Rust Community is interested in?

**Comment by Ralith** [comment]
Might be prudent to update the "Relationship to Tokio" section too, since it's fallen a bit out of date with the status quo and would be extra confusing in the face of this PR.

**Comment by kpp** [comment]
@Ralith will do in another PR after this gets land

**Comment by mexus** [comment]
> After 2 hours, this issue got 17 thumbs up. After 5 hours, it has 20. I recommend closing this issue as spam.

I beg you pardon, but are you really serious about this? Just want to clarify

**Comment by Fedcomp** [comment]
@spacejam could you explain how this issue is a spam?

Tokio got async await support in alpha versions. As far as i know neither async-std nor tokio is stable, and this project is tokio fork, so why not update it with alternatives?
In my opinion tokio is more established foundation for async in rust, so it would be fair to note them both into readme.

And why do you call my :+1: spam?

**Comment by vorot93** [comment]
@yoshuawuyts could you please clarify the reason for OP's ban in this repo?

**Comment by withoutboats** [comment]
I've decided to merge this PR, because there's no reason not to link to tokio, and to archive this repository, because it is deprecated, unmaintained, and of no use to anyone anymore. I am not going to merge #107 because reviewing the wording and stating the relationship to tokio presently is more effort than its worth.

Before I do that, though, I want to comment on the absurd situation of this pull request.

First of all, the users who find themselves unable to interact with this repo find themselves such because the repo is mine and I have personally blocked them from interacting with me further on GitHub. I cannot speak to any situation involving async-std, because I am not a contributor to that project.

I blocked these users because I do not believe they were acting in good faith in making and supporting this PR. It seems obvious that when a minor readme change to a deprecated project receives dozens of thumbs up within hours that something unusual is going on. In the larger context of known tensions betweens async-std (which shares contributors with this project) and tokio, and in my personal context of having found @kpp to be an aggressive and unpleasant person to engage with, what has happened here is obvious to me. That @kpp has gone on to use this PR on reddit to claim async-std's maintainers are not "kind and open" is the most disingenuous horseshit imaginable, one wonders if that was his initial hope for this PR, or just a happy outcome for him.

I have collaborated at length over the last several years with many people who are contributors to both async-std and tokio. There are people involved in both projects that I consider my personal friends. I am aware of the tensions between members of those projects, and I am privy to many of the details of those tensions which are not public - for good reason! - and which most people who see this PR will have no knowledge of. And even the contributors to some of those projects who I find it difficult to work with are, in my opinion, sympathetic at a fundamental level. But the people who have advanced this PR, with the only goal of hurting feelings and reputations, are not sympathetic to me. Why be so spiteful to people you've never met, who just want to write code in peace? What joy is there for you in ruining other peoples' days? How dare you pretend to be acting in good faith on behalf of the community! My code is written for people of better character than you, go away.

**Pull request merged**
